### ISSUE TITLE
struct.error when syncing

### ISSUE THREAD

**Issue by ScarletStar** [roboTJ101/ros_myo#4]
Hello again

I get the following error when trying to do the sync gesture

ubuntu@aristoteles:~$ rosrun ros_myo myo-rawNode.py
Initializing...
using device: /dev/ttyACM0
scanning...
scan response: Packet(80, 06, 00, [BD 00 E0 7C 93 8D 9C FF 00 FF 1F 09 08 50 69 4D 79 6F 00 00 00 02 01 06 11 06 42 48 12 4A 7F 2C 48 47 B9 DE 04 A9 01 00 06 D5])
firmware version: 1.4.1670.2
device name: PiMyo
PuTTY

Disconnecting...

Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 445, in <module>
    m.run(1)
  File "/home/ubuntu/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 204, in run
    self.bt.recv_packet(timeout)
  File "/home/ubuntu/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 87, in recv_packet
    self.handle_event(ret)
  File "/home/ubuntu/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 120, in handle_event
    h(p)
  File "/home/ubuntu/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 301, in handle_data
    typ, val, xdir = unpack('3B', pay)
  File "/home/ubuntu/catkin_ws/src/ros_myo/scripts/common.py", line 7, in unpack
    return struct.unpack('<' + fmt, *args)
struct.error: unpack requires a string argument of length 3

I tried outputting the payload as a string but it seems to be empty?
Please help, this is a really important project for me.

**Comment by roboTJ101** [comment]
My best advice for you is to try putting the 1.1.4.2 firmware on the armband, as that is what the library I developed used when I wrote this almost a year ago. I have no idea what Thalmic changed in their firmware between now and then.

**Comment by ScarletStar** [comment]
Thanks for the reply. I cannot find the firmware.Could you provide a link where I can download it?

**Comment by roboTJ101** [comment]
A cursory google search didn't yield a good download link, so I uploaded the firmware I used which happened to be chilling in my downloads folder.

**Comment by ScarletStar** [comment]
Bless, it works now!

Thank you so much my friend!

**Comment by roboTJ101** [comment]
Wait really? Cool!

**Comment by ScarletStar** [comment]
Also here's another workaround, if someone wants to use the newest firmware:

It seems like in line 301: 
```python
elif attr == 0x23:
  typ, val, xdir = unpack('3B', pay)
```

There are actually 6 bytes being transmitted. I'm not sure what the other 3 are. But just unpacking them without using them seems to work.

So changing that line to: 

```python
elif attr == 0x23:
  typ, val, xdir, unknown1, unknown2, unknown3 = unpack('6B', pay)
```


Hope that helps anyone.
